### ISSUE TITLE
Bug in code

### ISSUE THREAD

**Issue by yusuf1759** [delphi001/SAAMBE-3D#1]
Hi,
First of, great work for putting this together. It's extremely fast and really useful. However, I believe there is a bug that needs to be fixed. It's in the function `mutation_chemical`.

From your paper the categories of chemical features should be:
- Aliphatic (A, G, I, L, P, V)
- aromatic (F, W, Y)
- sulfur (C, M) 
- hydroxyl (S, T) 
- basic (R, H, K)
- acidic (D, E) and
- amide (N, Q)
However, C appear in two categories in the code in `('C','R','H','K')` and `('C','M')`. I fixed this in my local copy of the code, If you want I can push the changes. I just wanted to point this out.

**Comment by delphi001** [comment]
Hi,
Thank you for spotting the bug and reporting. We are fixing this issue

**Comment by yusuf1759** [comment]
You are welcome.

**Comment by yusuf1759** [comment]
@delphi001 Thanks for updating the code. Any chance that SAAMBE-3D-Seq will be open-sourced soon?

**Comment by delphi001** [comment]
Yes, we have made it open source. Added GNU GPL v3.0 License.

**Comment by yusuf1759** [comment]
Can you point me where I can find it? Maybe a link.

**Comment by delphi001** [comment]
Here is the license file: https://github.com/delphi001/SAAMBE-3D/blob/master/LICENSE

**Comment by delphi001** [comment]
You can get a copy of the repository/clone or download a zip, and use locally if you want link to SAAMBE-3D code.
Thank you.

**Comment by delphi001** [comment]
Hi.. It has been fixed in the code so closing the issue.
