### ISSUE TITLE
Explanation result

### ISSUE THREAD

**Issue by bsb2014** [delphi001/SAAMBE-3D#10]
Results are displayed here

Structure: ara1_real.BL00140001.pdb
Chain: N
Postion: 34
Original Amino Acid:N
Mutated Amino Acid: Y
ΔΔG Prediction:
0.38 Destabilizing

Does this result indicate that mutation Y results in destabilization? 
Was the ΔΔG calculated by ΔΔG=ΔGwt-ΔGmt or ΔΔG=ΔGmt - ΔGwt?

Thanks

**Comment by delphi001** [comment]
Yes, indeed this means a positive predicted ΔΔG implies destabilization. See in paper "We further evaluated the performance of SAAMBE-3D to assess the quality of classification of mutations into both destabilizing (ΔΔG is positive) and stabilizing mutations (ΔΔG is negative)". 

It is calculated as: ΔΔG=ΔGmt - ΔGwt
