### ISSUE TITLE
SAAMBE-3D vs mmCSM-PPI

### ISSUE THREAD

**Issue by bsb2014** [delphi001/SAAMBE-3D#11]
Hi there, I ran my case using both SAAMBE-3D and mmCSM-PPI.  SAAMBE-3D suggested a destabilization, but mmCSM-PPI suggested a stabilization. I am not sure which one is reliable. Based on your publication, SAAMBE-3D outperforms mmCSM-PPI. So is it safe to use the SAAMBE-3D result? Thanks

**Comment by bsb2014** [comment]
Can SAAMBE-3D predict trimer, such as MHCII (DIMER)+ peptide?  Thanks

**Comment by delphi001** [comment]
> Can SAAMBE-3D predict trimer, such as MHCII (DIMER)+ peptide? Thanks

Yes, you can. Actually, I t predicts ddG change between mutation chain with all other chains in the complex.

> Hi there, I ran my case using both SAAMBE-3D and mmCSM-PPI. SAAMBE-3D suggested a destabilization, but mmCSM-PPI suggested a stabilization. I am not sure which one is reliable. Based on your publication, SAAMBE-3D outperforms mmCSM-PPI. So is it safe to use the SAAMBE-3D result? Thanks

As SAAMBE-3D outperforms other methods. So, you can use SAAMBE-3D results.
