### ISSUE TITLE
reg:linear is now deprecated in favor of reg:squarederror

### ISSUE THREAD

**Issue by renee9904** [delphi001/SAAMBE-3D#7]
Hi, when I run the example code `python saambe-3d.py -i 1A22.pdb -f mutations_list.txt -d 1`
 it got error like:
 `@> 3113 atoms and 1 coordinate set(s) were parsed in 0.03s.
[15:17:50] WARNING: /Users/runner/miniforge3/conda-bld/xgboost_1588600962499/work/src/objective/regression_obj.cu:167: reg:linear is now deprecated in favor of reg:squarederror.`without any output. 
And the xgboost package I used is 1.0.2, I don't know how to fix it.
I would be grateful for any assistance you can provide.
Thank you.

**Comment by delphi001** [comment]
Hi, Thanks for writing. The above messages are log messages from the prody about the parsing PDB file, and XGBoost bacause the model was developed using an older version and library has deprecated some features in later versions. This didn't affect the prediction and still you should be able to get the results in the output file `output.out' created in the directory where you ran the code.

However, for clarity we have suppressed the log and warning messages and updated README with additional information. In case you have any further query let us know. Thank you!

**Comment by renee9904** [comment]
Thank you for your reply, I do see the output file. Thanks a lot!
